# Generated by Django 4.2.5 on 2023-09-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='food_item_name',
            field=models.IntegerField(null=True),
        ),
    ]
