# Generated by Django 4.2.5 on 2023-09-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_fooditem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='user',
        ),
    ]
