# Generated by Django 4.2.5 on 2023-09-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_notification_food_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='food_item_name',
            field=models.CharField(null=True),
        ),
    ]
