# Generated by Django 4.2.5 on 2023-09-28 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_remove_fooditem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
