# Generated by Django 4.2.5 on 2023-09-28 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_fooditem_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='owner',
        ),
    ]
