# Generated by Django 4.2.5 on 2023-09-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_fooditem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='owner',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
