# Generated by Django 4.2.5 on 2023-10-01 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('main_app', '0009_notification_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token'),
        ),
    ]
